### ISSUE TITLE
Latest release pinned is wrong

### ISSUE THREAD

**Issue by therourke** [fgl82/simplemenu#70]
Thanks for the updates! Just to let you know that the 'latest release' pinned on the releases page is still 4.6, so it is confusing on there.

**Comment by fgl82** [comment]
Thanks for the info, I didn't know.

I've just deleted 4.5.1, it's obsolete anyway.

I see 5.0 as the latest now, do you?

**Comment by fgl82** [comment]
Thanks for the info, I didn't know.
I've just deleted 4.5.1, it's obsolete anyway.
I see 5.0 as the latest now, do you?

**Comment by fgl82** [comment]
Fixed

**Comment by therourke** [comment]
Thanks for resolving this originally, but the issue is back. The list order in 'releases' is wrong, so people coming to find your latest version will get 5.0 instead. No idea why the list shows that way, but it does

**Comment by fgl82** [comment]
I fixed it again.

I have no idea whats going on.

Thanks for the heads up again.
